### ISSUE TITLE
[Feature]建议在输入序号下载音乐时增加输入过滤机制

### ISSUE THREAD

**Issue by 747761541** [0xHJK/music-dl#10]
**思路和建议**
建议在输入序号下载音乐时增加输入过滤机制
会有一部分人没有下载音乐就直接输入新的音乐音乐名称, 导致工具直接异常退出, 显得十分不健壮
增加输入过滤机制后, 若输入非法序号则会直接返回至主界面

**参考代码**
提供代码参考
main.py lin:42 增加:
``` python
    if [i for i in indexlist if not re.match(r"(^(\d*)-(\d*)$)|(^\d*$)", i)]:
        logger.warning('序号输入有误')
        return
```
(刚刚逻辑不太对, 重新改了下)

**Comment by 0xHJK** [comment]
多谢建议，我想过这个问题
但是考虑到这个是用户自己输入的，一般写错的概率比较低，如果用户不想按照规则输入其实给他提醒和直接退出是一样的

**Comment by 0xHJK** [comment]
已经添加该功能，感谢提供的建议
![image](https://user-images.githubusercontent.com/8033563/51652172-a80fb500-1fc9-11e9-90c5-6b172e5867ee.png)
