### ISSUE TITLE
[BUG]提示已保存到/tmp/xxx.mp3，然后歌曲找不到在哪里。本地路径下也没有

### ISSUE THREAD

**Issue by xiaomaguoguo** [0xHJK/music-dl#12]
**问题描述**
提交issues前，请检查是否是最新的代码，检查是否是Python3，检查依赖有没有安装完整

- 搜索的关键字：
- 出错的音乐源：
- 使用的命令：

**使用的环境**
- 操作系统版本：
- Python版本：

**截图**
使用`-v`参数运行，截取完整错误信息

**修改建议**

**Comment by 0xHJK** [comment]
`/tmp`是Linux环境下的临时目录，是我演示截图用的，你指定一个本地路径吧，或者不指定就是当前路径

**Comment by 747761541** [comment]
> `/tmp`是Linux环境下的临时目录，是我演示截图用的，你指定一个本地路径吧，或者不指定就是当前路径

linux环境下配置了config.py脚本中的outdir, 但是输出时还是输出到了当前目录.
跑了一遍debug发现它取到的路径就是"."

**Comment by 0xHJK** [comment]
> > `/tmp`是Linux环境下的临时目录，是我演示截图用的，你指定一个本地路径吧，或者不指定就是当前路径
> 
> linux环境下配置了config.py脚本中的outdir, 但是输出时还是输出到了当前目录.
> 跑了一遍debug发现它取到的路径就是"."

config.py中的变量会被click中的配置覆盖，新版本建议不要修改代码，常用参数建议使用`alias`
