### ISSUE TITLE
[Feature]想问一下， 获得的歌曲链接有效期是多少？

### ISSUE THREAD

**Issue by liuzhuoling2011** [0xHJK/music-dl#19]
**思路和建议**
我想知道，如果链接有效期是永久的， 那就可以缓存起来了

**参考代码**
提供链接参考 周杰伦，算什么男人
http://dl.stream.qqmusic.qq.com/M500001Js78a40BZU6.mp3?vkey=5F498B6A0644E477134DE84151D8AA0C45790BAD2601D90213A16331E2FDB5C395673AE3428C247DBF321D629DC058118E4BC3FAFFFBABBF&guid=2119652955&fromtag=1

**Comment by 0xHJK** [comment]
连接并不是永久的，大概几天就会失效
