### ISSUE TITLE
[BUG] pymusic-dl-2.2.0.tar.gz 中缺少 README.en.md 及 LICENSE

### ISSUE THREAD

**Issue by dctxmei** [0xHJK/music-dl#23]
**问题描述（Question description）**
提交issue前，请先检查是否是最新的代码、环境是否符合要求、依赖是否安装完整
请尽可能填写完整以下信息，方便排查问题，填写不完整可能不会受理
解决问题后请关闭issue，谢谢

- 搜索的关键字（Keyword）：
- 出错的音乐源（Music source）：
- 使用的命令（Command used）：python setup.py build

**使用的环境（Environment）**
- 安装方式（Installation method）：build
- music-dl版本（music-dl version）：2.2.0
- 操作系统版本（OS version）：Linux
- Python版本（Python version）：3.7

**截图**
使用`-v`参数运行，截取完整错误信息
Run with the `-v` parameter to get the full error message
![](https://i.loli.net/2019/04/04/5ca5a976d1cef.png)

**修改建议**
pymusic-dl-2.2.0.tar.gz 中缺少 README.en.md 及 LICENSE

**Comment by 0xHJK** [comment]
在2.2.1版本中修复了这个问题
