### ISSUE TITLE
[Feature]QQ音乐歌词及网易云音乐歌单

### ISSUE THREAD

**Issue by wwwpf** [0xHJK/music-dl#25]
**思路和建议**

来自之前写的一个小工具https://github.com/wwwpf/MusicDownloader

**参考代码**
提供代码参考

qq音乐歌词
```python
def get_song_lyrics(self, song):
    url = "https://c.y.qq.com/lyric/fcgi-bin/fcg_query_lyric_new.fcg"
    payload = {
        "songmid": song.mid,
        "loginUin": "0",
        "hostUin": "0",
        "format": "json",
        "inCharset": "utf8",
        "outCharset": "utf-8",
        "notice": "0",
        "platform": "yqq.json",
        "needNewCode": "0"
    }
    headers["referer"] = "https://y.qq.com/portal/player.html"
    r = requests.get(url, params=payload, headers=headers)
    json_data = r.json()
    lyric = json_data["lyric"]
    lyric = base64.b64decode(lyric).decode("utf-8")
```

网易云音乐歌单列表获取(`spider/netease.py`)
 #歌单数据非明文，需要解码，代码较长。可参考[网易云音乐歌单详情列表爬虫破解](https://blog.csdn.net/Deadeyehui/article/details/80708625)以及[`spider/netease.py`](https://github.com/wwwpf/MusicDownloader/blob/master/spider/netease.py)中的`get_playlist`函数
#17

**Comment by 0xHJK** [comment]
试了一下能成功获取歌词，非常感谢提供的思路和代码~
我打算重构一下项目，所以在后面的版本中再添加这个功能

**Comment by 0xHJK** [comment]
感谢提供的建议，目前已支持QQ音乐歌词和网易云歌单下载 <https://github.com/0xHJK/music-dl/tree/v3>
