### ISSUE TITLE
建议添加下载整张专辑及歌手热门歌曲的功能

### ISSUE THREAD

**Issue by 1235467** [0xHJK/music-dl#26]
**思路和建议**

**参考代码**
提供代码参考

**Comment by 0xHJK** [comment]
下个大版本会考虑添加歌单和专辑下载功能

**Comment by CoderTonyChan** [comment]
> 下个大版本会考虑添加歌单和专辑下载功能

发布计划是怎样呢？现在有几个网易云的歌单想下载 还有一些其他歌单 我在考虑要不要也做成网易云歌单 到时候一起下载

另外想请教作业是否有比较好的保存歌单的方法？

**Comment by 0xHJK** [comment]
@CoderTonyChan 正在写了，也没有明确的计划，应该这个月能搞定吧

**Comment by 0xHJK** [comment]
已支持网易云音乐歌单下载
