### ISSUE TITLE
[BUG]QQ音乐下载失败

### ISSUE THREAD

**Issue by kushao1267** [0xHJK/music-dl#32]
**问题描述（Question description）**

clone最新master分支，commit-id是c7652a05c8b741485443a888a0500ab451a1446c，安装后下载QQ音乐，显示`[2019-07-15 10:07:42] ERROR    | music_dl.core: 下载音乐失败`。

- 搜索的关键字（Keyword）：

赵雷

- 出错的音乐源（Music source）：

QQ

- 使用的命令（Command used）：

music-dl -k "赵雷"

**使用的环境（Environment）**

Python3

- 安装方式（Installation method）：

python3 setup.py install

- 操作系统版本（OS version）：

linux

- Python版本（Python version）：

python3

**修改建议**

应该是QQ反扒了，请求的接口返回403，建议更新策略。

**Comment by 0xHJK** [comment]
已修复

**Comment by lamda-lin** [comment]
现在又不行了

**Comment by 0xHJK** [comment]
@lamda-lin 一般歌曲可以的，付费歌曲不行了，比如周杰伦的
