### ISSUE TITLE
[BUG] LICENSE 及 README.en.md 被放置於非標準路徑中

### ISSUE THREAD

**Issue by dctxmei** [0xHJK/music-dl#34]
**问题描述（Question description）**
提交issue前，请先检查是否是最新的代码、环境是否符合要求、依赖是否安装完整
请尽可能填写完整以下信息，方便排查问题，填写不完整可能不会受理
解决问题后请关闭issue，谢谢

- 搜索的关键字（Keyword）：
- 出错的音乐源（Music source）：
- 使用的命令（Command used）：

```
$ python setup.py install --root="$pkgdir/" --optimize=1 --skip-build
```

or

```
$ git clone https://aur.archlinux.org/music-dl.git && cd music-dl
$ extra-x86_64-build -c
```

**使用的环境（Environment）**
- 安装方式（Installation method）：build
- music-dl版本（music-dl version）：3.0.0
- 操作系统版本（OS version）：Arch Linux
- Python版本（Python version）：3.7

**截图**
使用`-v`参数运行，截取完整错误信息
Run with the `-v` parameter to get the full error message
![](https://i.loli.net/2019/09/12/R3zCmBafEWHhZqK.png)

**修改建议**
請將 [LICENSE 及 README.en.md](https://github.com/0xHJK/music-dl/commit/c7652a05c8b741485443a888a0500ab451a1446c) 放置於標準路徑當中

如下：

```
usr/share/licenses/music-dl/LICENSE
usr/share/music-dl/README
```

![](https://i.loli.net/2019/09/12/X9BvL7ZIKkEFT65.png)

**Comment by 0xHJK** [comment]
感谢建议，考虑到classifiers中已经有lisence，long_description也包含了说明，所以直接将该行删除了

**Comment by dctxmei** [comment]
END
