### ISSUE TITLE
下载周杰伦的告白气球报错，来源是酷狗

### ISSUE THREAD

**Issue by paozhuanyinyu** [0xHJK/music-dl#38]
**问题描述（Question description）**
提交issue前，请先检查是否是最新的代码、环境是否符合要求、依赖是否安装完整
请尽可能填写完整以下信息，方便排查问题，填写不完整可能不会受理
解决问题后请关闭issue，谢谢

- 搜索的关键字（Keyword）：周杰伦
- 出错的音乐源（Music source）：酷狗
- 使用的命令（Command used）：music-dl -k 周杰伦 --lyrics -v

**使用的环境（Environment）**
- 安装方式（Installation method）：pip3
- music-dl版本（music-dl version）：3.0.1
- 操作系统版本（OS version）：MacOS 10.15
- Python版本（Python version）：3.7.4

**截图**
使用`-v`参数运行，截取完整错误信息
Run with the `-v` parameter to get the full error message
yukai@bogon ~ % music-dl -k 周杰伦 --lyrics -v

Searching 周杰伦 from ... KUGOU ... QQ ... NETEASE ... BAIDU ...
+------+----------------------------------+----------------------+---------+---------+----------------------------------+---------+
| 序号 | 歌名                             | 歌手                 | 大小    | 时长    | 专辑                             | 来源    |
+------+----------------------------------+----------------------+---------+---------+----------------------------------+---------+
| 0    | 骑士精神                         | 蔡依林、周杰伦       | 3.93MB  | 0:04:17 | 看我72变                         | NETEASE |
| 1    | 布拉格广场                       | 蔡依林、周杰伦       | 4.5MB   | 0:04:54 | 看我72变                         | NETEASE |
| 2    | 刀马旦                           | 李玟、周杰伦         | 2.96MB  | 0:03:13 | Promise                          | NETEASE |
| 3    | 周杰伦婚礼进行曲                 | 忘了笔迹             | 4.92MB  | 0:02:08 | 周杰伦婚礼进行曲                 | BAIDU   |
| 4    | 周杰伦婚礼音乐（女生吉他弹唱版） | 张一清（白桦树娃娃） | 1.86MB  | 0:02:01 | 周杰伦婚礼音乐（女生吉他弹唱版） | BAIDU   |
| 5    | 周杰伦                           | 山弟                 | 10.26MB | 0:04:28 | 周杰伦                           | BAIDU   |
| 6    | 爱的飞行日记                     | 周杰伦、杨瑞代       | 3.91MB  | 0:04:15 | 跨时代                           | KUGOU   |
| 7    | 祝我生日快乐                     | 周杰伦,温岚          | 9.94MB  | 0:04:18 | 爱回温                           | BAIDU   |
| 8    | 屋顶                             | 周杰伦,温岚          | 12.24MB | 0:05:19 | 爱回温                           | BAIDU   |
| 9    | 说好不哭（with 五月天阿信）      | 周杰伦               | 3.39MB  | 0:03:42 | 说好不哭（with 五月天阿信）      | QQ      |
| 10   | 说好不哭(with 五月天阿信)        | 周杰伦               | 3.39MB  | 0:03:42 | 说好不哭(with 五月天阿信)        | KUGOU   |
| 11   | 晴天                             | 周杰伦               | 4.12MB  | 0:04:29 | 叶惠美                           | KUGOU   |
| 12   | 告白气球                         | 周杰伦               | 3.28MB  | 0:03:35 | 周杰伦的床边故事                 | KUGOU   |
| 13   | 听妈妈的话                       | 周杰伦               | 4.06MB  | 0:04:25 | 依然范特西                       | KUGOU   |
| 14   | 七里香                           | 周杰伦               | 4.57MB  | 0:04:59 | 七里香                           | QQ      |
| 15   | 一路向北                         | 周杰伦               | 4.51MB  | 0:04:55 | J III MP3 Player                 | QQ      |
+------+----------------------------------+----------------------+---------+---------+----------------------------------+---------+

请输入下载序号，支持形如 0 3-5 8 的格式，输入 N 跳过下载
 >>: 12

[11:15:20] ERROR    | music_dl.song: 周杰伦 - 告白气球.mp3 @KUGOU is not available.
请输入要搜索的歌曲，或Ctrl+C退出

**修改建议**

**Comment by 0xHJK** [comment]
接口被屏蔽了，用咪咕的
```
music-dl -k "告白气球" -s migu
```

**Comment by paozhuanyinyu** [comment]
咪咕可以下载，我关issiue啦
