### ISSUE TITLE
[BUG]music-dl -p 报错：Invalid url

### ISSUE THREAD

**Issue by VayneDy** [0xHJK/music-dl#39]
用-p下载歌单报错，这个url我在浏览器中能打开
https://y.qq.com/n/yqq/playlist/3853681382.html

![image](https://user-images.githubusercontent.com/29139680/70780658-026f5b00-1dc0-11ea-894e-e2ff45c457e9.png)

**Comment by 0xHJK** [comment]
还没有支持QQ音乐歌单，目前只支持网易歌单

**Comment by VayneDy** [comment]
OK,3Q.
