### ISSUE TITLE
pycrypto库安装困难, 网易云请求体AES加密可否使用其他方法?

### ISSUE THREAD

**Issue by 747761541** [0xHJK/music-dl#6]
试了好多个环境, 安装pycrypto库是真的麻烦

**Comment by 0xHJK** [comment]
pycrypto库已经换掉了，你试试新的代码

**Comment by 747761541** [comment]
> pycrypto库已经换掉了，你试试新的代码

哈哈哈哈, 刚看到, pycryptodome已经安装成功了!
