### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by Innocence-y** [0xHJK/music-dl#8]
好像不能用了，获取歌曲失败

**Comment by 0xHJK** [comment]
使用`-v`参数，然后把详情截图发上来

**Comment by Innocence-y** [comment]
![image](https://user-images.githubusercontent.com/22276020/51591118-1fd8d380-1f27-11e9-9000-a3a97c7df9e7.png)

**Comment by Innocence-y** [comment]
![image](https://user-images.githubusercontent.com/22276020/51591139-2d8e5900-1f27-11e9-82a7-e75f62847aad.png)

**Comment by Innocence-y** [comment]
是被屏蔽了吗还是接口不能用了

**Comment by 0xHJK** [comment]
`git pull`更新一下代码试试

**Comment by Innocence-y** [comment]
![image](https://user-images.githubusercontent.com/22276020/51647823-3d567d80-1fb9-11e9-9f10-98c993196185.png)
这个是什么问题啊，你有遇到吗，谢谢！

**Comment by 0xHJK** [comment]
你好，尝试使用一下这个版本是否解决你的问题：
https://github.com/0xHJK/music-dl/archive/bugfix.zip

**Comment by Innocence-y** [comment]
![Uploading image.png…]()还是不可以，是我的环境的问题吗？谢谢！！

**Comment by 0xHJK** [comment]
你把你的环境根据模板填一下呀，我不知道你的环境是什么才问你😂️
上传的图好像也裂了
